export const customerData = [
  {
    id: 1,
    name: "John Smith",
    email: "john.smith@example.com",
    phoneNumber: "+1234567890",
    streetAddress: "10 Epic Ave",
    suburb: "Oakland",
  },
  {
    id: 2,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    phoneNumber: "+1987654321",
    suburb: "Springfield",
  },
  {
    id: 3,
    name: "Emily Brown",
    email: "emily.brown@example.com",
    phoneNumber: "+1543219876",
    suburb: "Maplewood",
  },
  {
    id: 4,
    name: "Michael Davis",
    email: "michael.davis@example.com",
    phoneNumber: "+1357924680",
    suburb: "Riverside",
  },
  {
    id: 5,
    name: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    phoneNumber: "+1122334455",
    suburb: "Pinecrest",
  },
  {
    id: 6,
    name: "David Martinez",
    email: "david.martinez@example.com",
    phoneNumber: "+1654321890",
    suburb: "Greenville",
  },
  {
    id: 7,
    name: "Jennifer Lee",
    email: "jennifer.lee@example.com",
    phoneNumber: "+1789054321",
    suburb: "Brookside",
  },
  {
    id: 8,
    name: "Christopher Taylor",
    email: "chris.taylor@example.com",
    phoneNumber: "+1987651234",
    suburb: "Sunset Hills",
  },
  {
    id: 9,
    name: "Jessica Hernandez",
    email: "jessica.hernandez@example.com",
    phoneNumber: "+1876543210",
    suburb: "Willow Creek",
  },
  {
    id: 10,
    name: "Daniel Clark",
    email: "daniel.clark@example.com",
    phoneNumber: "+1432156789",
    suburb: "Hillcrest",
  },
  {
    id: 11,
    name: "Lauren White",
    email: "lauren.white@example.com",
    phoneNumber: "+1324567890",
    suburb: "Riverdale",
  },
  {
    id: 12,
    name: "Ryan Garcia",
    email: "ryan.garcia@example.com",
    phoneNumber: "+1789345678",
    suburb: "Highland Park",
  },
  {
    id: 13,
    name: "Amanda King",
    email: "amanda.king@example.com",
    phoneNumber: "+1567890123",
    suburb: "Meadowbrook",
  },
  {
    id: 14,
    name: "Kevin Scott",
    email: "kevin.scott@example.com",
    phoneNumber: "+1654312908",
    suburb: "Hilltop",
  },
  {
    id: 15,
    name: "Olivia Adams",
    email: "olivia.adams@example.com",
    phoneNumber: "+1345678901",
    suburb: "Greenfield",
  },
];
