import {
  ArrowDown,
  ArrowRight,
  ArrowUpRight,
  Calendar,
  Check,
  ChevronLeft,
  DollarSign,
  EllipsisVertical,
  Ghost,
  Info,
  Laptop,
  Loader2,
  Mail,
  MapPin,
  Menu,
  Moon,
  Pencil,
  Phone,
  Plus,
  ReceiptText,
  Sun,
  Trash,
  User,
  Users,
} from "lucide-react";

export const Icons = {
  add: Plus,
  arrowDown: ArrowDown,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  back: ChevronLeft,
  calendar: Calendar,
  check: Check,
  delete: Trash,
  edit: Pencil,
  ghost: Ghost,
  info: Info,
  invoice: ReceiptText,
  location: MapPin,
  mail: Mail,
  menu: Menu,
  money: DollarSign,
  moon: Moon,
  phone: Phone,
  spinner: Loader2,
  subMenu: EllipsisVertical,
  sun: Sun,
  system: Laptop,
  user: User,
  users: Users,
};
